name = "TriMeshGame"
uuid = "6fe937b6-a686-4c05-aa43-439f88a41e40"
authors = ["Arjun <arjun.narayanan91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
